keys:
  - &bbtux age17zy4zw0qw5xhr00yjfaxffmnznkle28aplvqtfu8yh7tfxcv0pvq5zg70v
  - &juliogm age1sg53svm4fe6l770l65q2dg42jh0a6e4jfj28y58eafv84x3kp3uq2a9s88
  - &zuko age1u6kfrscrx9qvk2mymm2ur5nwxge3punvmdszwcyg4mcmw4kvnv9ss4mfay
  # - &katara age1...
  # - &appa age1... # TODO: run `ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub` on appa
creation_rules:
  - path_regex: secrets/zuko\.yaml$
    key_groups:
      - age:
          - *bbtux
          - *zuko
  - path_regex: secrets/katara\.yaml$
    key_groups:
      - age:
          - *bbtux
          # - *katara
  - path_regex: secrets/juliogm\.yaml$
    key_groups:
      - age:
          - *bbtux
          - *juliogm
          - *zuko
  - path_regex: secrets/appa\.yaml$
    key_groups:
      - age:
          - *bbtux
          # - *appa
  - path_regex: secrets/work\.yaml$
    key_groups:
      - age:
          - *bbtux
          - *zuko
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *bbtux
          - *zuko
          # - *katara
