{ self, ... }:
{
  flake.nixosModules.crowdsec =
    { config, pkgs, ... }:
    {
      imports = [ self.nixosModules.sops ];

      # Console enrollment key (optional). Add to secrets/appa.yaml:
      #
      #   crowdsec_console_key: "<from cscli console enroll on app.crowdsec.net>"
      #
      # An empty string is also fine — the systemd unit below skips
      # enrollment when the value is blank, so hosts without a Console
      # account can still build cleanly.
      sops.secrets.crowdsec_console_key = {
        sopsFile = "${self}/secrets/appa.yaml";
      };

      # Workaround for an upstream NixOS module bug: crowdsec.service is set
      # up with DynamicUser=true but without StateDirectory=, so /var/lib/
      # crowdsec ends up as a dangling symlink and the setup script can't
      # mkdir through it. Setting StateDirectory explicitly makes systemd
      # create /var/lib/private/crowdsec owned by the dynamic user.
      systemd.services.crowdsec.serviceConfig.StateDirectory = "crowdsec";

      # The upstream NixOS module renders the daemon config to a /nix/store
      # path and passes it via `-c=<path>`, but raw cscli (used by upstream's
      # own crowdsec-firewall-bouncer-register) defaults to /etc/crowdsec/
      # config.yaml. Mirror the same content there so raw cscli works
      # without a wrapper. Generated from the merged settings tree, so it
      # always matches what the daemon sees.
      environment.etc."crowdsec/config.yaml".source =
        (pkgs.formats.yaml { }).generate "crowdsec-config.yaml"
          config.services.crowdsec.settings.general;

      services.crowdsec = {
        enable = true;
        # `cscli hub update` runs daily so parser / scenario / blocklist
        # definitions stay current.
        autoUpdateService = true;

        # The upstream module defaults api.server.enable=false; without this
        # the LAPI never binds and every bouncer can't connect. We want the
        # local agent + bouncers integration, so flip it on.
        settings.general.api.server.enable = true;

        # Where machine credentials get auto-generated by `cscli machine add
        # --auto` in the setup script (and read by the agent on every start).
        # Must be set when api.server.enable=true, otherwise the upstream
        # module's setup script null-derefs cfg.settings.lapi.credentialsFile.
        settings.lapi.credentialsFile = "/etc/crowdsec/local_api_credentials.yaml";

        # CrowdSec's default API port (8080) collides with qbittorrent's
        # webuiPort. Pick 6868 instead -- 6060 is taken by the upstream-
        # defaulted Prometheus exporter, and we'd rather not move that.
        # Firewall and Caddy bouncers reference this port (see crowdsec-
        # bouncers.nix and reverse-proxy.nix).
        settings.general.api.server.listen_uri = "127.0.0.1:6868";

        # Generic collections that aren't tied to one specific service.
        # Per-service collections + acquisitions live in the service module
        # that produces the logs (see e.g. reverse-proxy.nix for caddy,
        # openssh.nix for sshd, jellyfin.nix / forgejo.nix / plex.nix for
        # their app-specific parsers).
        hub.collections = [
          "crowdsecurity/linux"
          "crowdsecurity/base-http-scenarios"
          "crowdsecurity/http-cve"
          "crowdsecurity/http-dos"
          "crowdsecurity/whitelist-good-actors"
        ];

        # Whitelist trusted local networks so internal traffic never gets
        # banned, even if a misconfigured app triggers an HTTP scenario.
        localConfig.parsers.s02Enrich = [
          {
            name = "den/lan-whitelist";
            description = "Trust local networks";
            whitelist = {
              reason = "trusted LAN ranges";
              ip = [ "127.0.0.1" ];
              cidr = [
                "10.0.0.0/8"
                "172.16.0.0/12"
                "192.168.0.0/16"
              ];
            };
          }
        ];
      };

      # Console enrollment is idempotent in spirit but cscli prompts if
      # already enrolled, so we skip when local_api_credentials shows a
      # login. The user still has to approve the agent in the Console UI
      # once — this just kicks the request automatically.
      systemd.services.crowdsec-console-enroll = {
        description = "Enroll the local agent with the CrowdSec Console";
        after = [ "crowdsec.service" ];
        wants = [ "crowdsec.service" ];
        wantedBy = [ "multi-user.target" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        path = [ config.services.crowdsec.package ];
        script = ''
          key=$(cat ${config.sops.secrets.crowdsec_console_key.path})
          if [ -z "$key" ]; then
            echo "no console key configured; skipping enrollment"
            exit 0
          fi
          if [ -e /etc/crowdsec/online_api_credentials.yaml ] \
             && grep -q '^login:' /etc/crowdsec/online_api_credentials.yaml; then
            echo "already enrolled with the Console; skipping"
            exit 0
          fi
          cscli console enroll "$key"
        '';
      };
    };
}
